name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the node version you are using

    - name: Install dependencies
      run: npm install

    - name: Set environment variables from secrets
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "ANOTHER_SECRET=${{ secrets.ANOTHER_SECRET }}" >> .env

    - name: Run the application
      run: npm start  # Replace with your start script if different

    - name: Run tests
      run: npm test  # If you have tests
